name: calendar_flutter
description: "타임스프레드 캘린더 모듈 프로젝트"

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  go_router: ^14.8.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.1
  freezed: ^2.5.0
  json_serializable: ^6.9.0
  drift_dev: ^2.23.1

flutter:
  uses-material-design: true
  assets:
    - packages/calendar_flutter/assets/icons/arrow_left_navigation.webp
    - packages/calendar_flutter/assets/icons/arrow_right.webp
    - packages/calendar_flutter/assets/icons/bell.webp
    - packages/calendar_flutter/assets/icons/calendar.webp
    - packages/calendar_flutter/assets/icons/clock.webp
    - packages/calendar_flutter/assets/icons/close_navigation.webp
    - packages/calendar_flutter/assets/icons/check_white.webp
    - packages/calendar_flutter/assets/icons/chevron_down.webp
    - packages/calendar_flutter/assets/icons/chevron_right.webp
    - packages/calendar_flutter/assets/icons/chevron_up.webp
    - packages/calendar_flutter/assets/icons/delete.webp
    - packages/calendar_flutter/assets/icons/keyboard.webp
    - packages/calendar_flutter/assets/icons/lock.webp
    - packages/calendar_flutter/assets/icons/logo_google.webp
    - packages/calendar_flutter/assets/icons/menu.webp
    - packages/calendar_flutter/assets/icons/plus.webp
    - packages/calendar_flutter/assets/icons/plus_white.webp
    - packages/calendar_flutter/assets/icons/repeat.webp
    - packages/calendar_flutter/assets/icons/settings.webp

    - packages/calendar_flutter/assets/images/calendar_select.webp
    - packages/calendar_flutter/assets/images/theme_basic.webp
    - packages/calendar_flutter/assets/images/theme_dark1.webp
    - packages/calendar_flutter/assets/images/theme_dark2.webp
    - packages/calendar_flutter/assets/images/theme_mono.webp
    - packages/calendar_flutter/assets/images/theme_note1.webp
    - packages/calendar_flutter/assets/images/theme_note2.webp
    - packages/calendar_flutter/assets/images/theme_pink.webp
    - packages/calendar_flutter/assets/images/theme_purple.webp
    - packages/calendar_flutter/assets/images/theme_spring.webp

